### ISSUE TITLE
Je ne vois pas l'onglet d'importation des données

### ISSUE THREAD

**Issue by bayo9999** [SARRA-cropmodels/SARRA-H#1]
J'essaye d'important manuellement des données de stations sur SARRAH.
Mais mon problème est que je n'arrive pas à voir l'onglet importation pour pouvoir cliquer dessus (voir capture).
Avez-vous une solution sur ça ?
<img width="558" alt="Capture1111111111111111" src="https://github.com/SARRA-cropmodels/SARRA-H/assets/139163774/3446dea2-174d-4655-8656-a6740b9d3226">

**Comment by codename5281** [comment]
Bonjour @bayo9999 ,

Avez-vous essayé de redémarrer l'application en mode administrateur (clic droit -> Exécuter en tant qu'administrateur).
Normalement, vous devriez obtenir la fenêtre d'importation suivante, avec un bouton "importation" apparent. 

![image](https://github.com/SARRA-cropmodels/SARRA-H/assets/44723543/5f985589-6a41-422b-b689-a005f2052d22)

Aussi, avez-vous tenté de redimensionner la fenêtre ?
A vous lire,
J.

**Comment by codename5281** [comment]
Après échanges mail, le problème semble avoir lieu sous Windows 10, sans plus de détails. Une installation sur une autre machine a résolu le problème. Je suppose le rôle d'une configuration particulière des thèmes Windows qui ne convient pas à l'affichage du logiciel.
